// This would typically be in a database, but for now we'll use a comprehensive static dataset
export interface Country {
  code: string;
  name: string;
  continent: string;
}

export interface City {
  id: string;
  name: string;
  countryCode: string;
  countryName: string;
  popular?: boolean;
}

export interface Airport {
  iata: string;
  icao: string;
  name: string;
  cityId: string;
  cityName: string;
  countryCode: string;
  countryName: string;
  popular?: boolean;
}

export const COUNTRIES: Country[] = [
  // North America
  { code: 'US', name: 'United States', continent: 'North America' },
  { code: 'CA', name: 'Canada', continent: 'North America' },
  { code: 'MX', name: 'Mexico', continent: 'North America' },
  { code: 'GT', name: 'Guatemala', continent: 'North America' },
  { code: 'CU', name: 'Cuba', continent: 'North America' },
  { code: 'JM', name: 'Jamaica', continent: 'North America' },
  { code: 'CR', name: 'Costa Rica', continent: 'North America' },
  { code: 'PA', name: 'Panama', continent: 'North America' },
  
  // Europe
  { code: 'GB', name: 'United Kingdom', continent: 'Europe' },
  { code: 'FR', name: 'France', continent: 'Europe' },
  { code: 'DE', name: 'Germany', continent: 'Europe' },
  { code: 'IT', name: 'Italy', continent: 'Europe' },
  { code: 'ES', name: 'Spain', continent: 'Europe' },
  { code: 'NL', name: 'Netherlands', continent: 'Europe' },
  { code: 'CH', name: 'Switzerland', continent: 'Europe' },
  { code: 'AT', name: 'Austria', continent: 'Europe' },
  { code: 'BE', name: 'Belgium', continent: 'Europe' },
  { code: 'PT', name: 'Portugal', continent: 'Europe' },
  { code: 'GR', name: 'Greece', continent: 'Europe' },
  { code: 'NO', name: 'Norway', continent: 'Europe' },
  { code: 'SE', name: 'Sweden', continent: 'Europe' },
  { code: 'DK', name: 'Denmark', continent: 'Europe' },
  { code: 'FI', name: 'Finland', continent: 'Europe' },
  { code: 'IS', name: 'Iceland', continent: 'Europe' },
  { code: 'IE', name: 'Ireland', continent: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', continent: 'Europe' },
  { code: 'HU', name: 'Hungary', continent: 'Europe' },
  { code: 'PL', name: 'Poland', continent: 'Europe' },
  { code: 'HR', name: 'Croatia', continent: 'Europe' },
  { code: 'RS', name: 'Serbia', continent: 'Europe' },
  { code: 'BG', name: 'Bulgaria', continent: 'Europe' },
  { code: 'RO', name: 'Romania', continent: 'Europe' },
  { code: 'SK', name: 'Slovakia', continent: 'Europe' },
  { code: 'SI', name: 'Slovenia', continent: 'Europe' },
  { code: 'LT', name: 'Lithuania', continent: 'Europe' },
  { code: 'LV', name: 'Latvia', continent: 'Europe' },
  { code: 'EE', name: 'Estonia', continent: 'Europe' },
  { code: 'TR', name: 'Turkey', continent: 'Europe/Asia' },
  { code: 'RU', name: 'Russia', continent: 'Europe/Asia' },
  { code: 'UA', name: 'Ukraine', continent: 'Europe' },
  
  // Asia
  { code: 'JP', name: 'Japan', continent: 'Asia' },
  { code: 'KR', name: 'South Korea', continent: 'Asia' },
  { code: 'CN', name: 'China', continent: 'Asia' },
  { code: 'TH', name: 'Thailand', continent: 'Asia' },
  { code: 'SG', name: 'Singapore', continent: 'Asia' },
  { code: 'MY', name: 'Malaysia', continent: 'Asia' },
  { code: 'ID', name: 'Indonesia', continent: 'Asia' },
  { code: 'PH', name: 'Philippines', continent: 'Asia' },
  { code: 'VN', name: 'Vietnam', continent: 'Asia' },
  { code: 'IN', name: 'India', continent: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', continent: 'Asia' },
  { code: 'SA', name: 'Saudi Arabia', continent: 'Asia' },
  { code: 'QA', name: 'Qatar', continent: 'Asia' },
  { code: 'KW', name: 'Kuwait', continent: 'Asia' },
  { code: 'BH', name: 'Bahrain', continent: 'Asia' },
  { code: 'OM', name: 'Oman', continent: 'Asia' },
  { code: 'JO', name: 'Jordan', continent: 'Asia' },
  { code: 'LB', name: 'Lebanon', continent: 'Asia' },
  { code: 'IL', name: 'Israel', continent: 'Asia' },
  { code: 'PK', name: 'Pakistan', continent: 'Asia' },
  { code: 'BD', name: 'Bangladesh', continent: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', continent: 'Asia' },
  { code: 'MM', name: 'Myanmar', continent: 'Asia' },
  { code: 'KH', name: 'Cambodia', continent: 'Asia' },
  { code: 'LA', name: 'Laos', continent: 'Asia' },
  { code: 'MN', name: 'Mongolia', continent: 'Asia' },
  { code: 'NP', name: 'Nepal', continent: 'Asia' },
  { code: 'BT', name: 'Bhutan', continent: 'Asia' },
  { code: 'MV', name: 'Maldives', continent: 'Asia' },
  { code: 'TW', name: 'Taiwan', continent: 'Asia' },
  { code: 'HK', name: 'Hong Kong', continent: 'Asia' },
  { code: 'MO', name: 'Macau', continent: 'Asia' },
  
  // Oceania
  { code: 'AU', name: 'Australia', continent: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', continent: 'Oceania' },
  { code: 'FJ', name: 'Fiji', continent: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', continent: 'Oceania' },
  { code: 'NC', name: 'New Caledonia', continent: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', continent: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', continent: 'Oceania' },
  { code: 'TO', name: 'Tonga', continent: 'Oceania' },
  { code: 'WS', name: 'Samoa', continent: 'Oceania' },
  { code: 'KI', name: 'Kiribati', continent: 'Oceania' },
  
  // South America
  { code: 'BR', name: 'Brazil', continent: 'South America' },
  { code: 'AR', name: 'Argentina', continent: 'South America' },
  { code: 'CL', name: 'Chile', continent: 'South America' },
  { code: 'PE', name: 'Peru', continent: 'South America' },
  { code: 'CO', name: 'Colombia', continent: 'South America' },
  { code: 'VE', name: 'Venezuela', continent: 'South America' },
  { code: 'EC', name: 'Ecuador', continent: 'South America' },
  { code: 'BO', name: 'Bolivia', continent: 'South America' },
  { code: 'PY', name: 'Paraguay', continent: 'South America' },
  { code: 'UY', name: 'Uruguay', continent: 'South America' },
  { code: 'GY', name: 'Guyana', continent: 'South America' },
  { code: 'SR', name: 'Suriname', continent: 'South America' },
  { code: 'GF', name: 'French Guiana', continent: 'South America' },
  
  // Africa
  { code: 'ZA', name: 'South Africa', continent: 'Africa' },
  { code: 'EG', name: 'Egypt', continent: 'Africa' },
  { code: 'MA', name: 'Morocco', continent: 'Africa' },
  { code: 'KE', name: 'Kenya', continent: 'Africa' },
  { code: 'TZ', name: 'Tanzania', continent: 'Africa' },
  { code: 'NG', name: 'Nigeria', continent: 'Africa' },
  { code: 'GH', name: 'Ghana', continent: 'Africa' },
  { code: 'ET', name: 'Ethiopia', continent: 'Africa' },
  { code: 'UG', name: 'Uganda', continent: 'Africa' },
  { code: 'RW', name: 'Rwanda', continent: 'Africa' },
  { code: 'BW', name: 'Botswana', continent: 'Africa' },
  { code: 'NA', name: 'Namibia', continent: 'Africa' },
  { code: 'ZM', name: 'Zambia', continent: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', continent: 'Africa' },
  { code: 'MW', name: 'Malawi', continent: 'Africa' },
  { code: 'MZ', name: 'Mozambique', continent: 'Africa' },
  { code: 'MG', name: 'Madagascar', continent: 'Africa' },
  { code: 'MU', name: 'Mauritius', continent: 'Africa' },
  { code: 'SC', name: 'Seychelles', continent: 'Africa' },
  { code: 'RE', name: 'Réunion', continent: 'Africa' },
  { code: 'TN', name: 'Tunisia', continent: 'Africa' },
  { code: 'DZ', name: 'Algeria', continent: 'Africa' },
  { code: 'LY', name: 'Libya', continent: 'Africa' },
  { code: 'SD', name: 'Sudan', continent: 'Africa' },
  { code: 'SS', name: 'South Sudan', continent: 'Africa' },
  { code: 'ER', name: 'Eritrea', continent: 'Africa' },
  { code: 'DJ', name: 'Djibouti', continent: 'Africa' },
  { code: 'SO', name: 'Somalia', continent: 'Africa' },
  { code: 'SN', name: 'Senegal', continent: 'Africa' },
  { code: 'ML', name: 'Mali', continent: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', continent: 'Africa' },
  { code: 'NE', name: 'Niger', continent: 'Africa' },
  { code: 'TD', name: 'Chad', continent: 'Africa' },
  { code: 'CM', name: 'Cameroon', continent: 'Africa' },
  { code: 'CF', name: 'Central African Republic', continent: 'Africa' },
  { code: 'CD', name: 'Democratic Republic of the Congo', continent: 'Africa' },
  { code: 'CG', name: 'Republic of the Congo', continent: 'Africa' },
  { code: 'GA', name: 'Gabon', continent: 'Africa' },
  { code: 'GQ', name: 'Equatorial Guinea', continent: 'Africa' },
  { code: 'ST', name: 'São Tomé and Príncipe', continent: 'Africa' },
  { code: 'AO', name: 'Angola', continent: 'Africa' },
  { code: 'CV', name: 'Cape Verde', continent: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau', continent: 'Africa' },
  { code: 'GN', name: 'Guinea', continent: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', continent: 'Africa' },
  { code: 'LR', name: 'Liberia', continent: 'Africa' },
  { code: 'CI', name: 'Ivory Coast', continent: 'Africa' },
  { code: 'GM', name: 'Gambia', continent: 'Africa' },
  { code: 'BI', name: 'Burundi', continent: 'Africa' },
  { code: 'KM', name: 'Comoros', continent: 'Africa' },
  { code: 'YT', name: 'Mayotte', continent: 'Africa' },
];

export const CITIES: City[] = [
  // US Cities
  { id: 'nyc', name: 'New York', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'lax', name: 'Los Angeles', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'chi', name: 'Chicago', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'mia', name: 'Miami', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'sfo', name: 'San Francisco', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'sea', name: 'Seattle', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'bos', name: 'Boston', countryCode: 'US', countryName: 'United States', popular: true },
  { id: 'atl', name: 'Atlanta', countryCode: 'US', countryName: 'United States' },
  { id: 'dfw', name: 'Dallas', countryCode: 'US', countryName: 'United States' },
  { id: 'den', name: 'Denver', countryCode: 'US', countryName: 'United States' },
  { id: 'las', name: 'Las Vegas', countryCode: 'US', countryName: 'United States' },
  { id: 'phx', name: 'Phoenix', countryCode: 'US', countryName: 'United States' },
  { id: 'dc', name: 'Washington DC', countryCode: 'US', countryName: 'United States' },
  { id: 'orl', name: 'Orlando', countryCode: 'US', countryName: 'United States' },
  
  // European Cities
  { id: 'lon', name: 'London', countryCode: 'GB', countryName: 'United Kingdom', popular: true },
  { id: 'par', name: 'Paris', countryCode: 'FR', countryName: 'France', popular: true },
  { id: 'rom', name: 'Rome', countryCode: 'IT', countryName: 'Italy', popular: true },
  { id: 'bcn', name: 'Barcelona', countryCode: 'ES', countryName: 'Spain', popular: true },
  { id: 'ams', name: 'Amsterdam', countryCode: 'NL', countryName: 'Netherlands', popular: true },
  { id: 'ber', name: 'Berlin', countryCode: 'DE', countryName: 'Germany', popular: true },
  { id: 'vie', name: 'Vienna', countryCode: 'AT', countryName: 'Austria', popular: true },
  { id: 'pra', name: 'Prague', countryCode: 'CZ', countryName: 'Czech Republic', popular: true },
  { id: 'bud', name: 'Budapest', countryCode: 'HU', countryName: 'Hungary', popular: true },
  { id: 'mad', name: 'Madrid', countryCode: 'ES', countryName: 'Spain' },
  { id: 'mil', name: 'Milan', countryCode: 'IT', countryName: 'Italy' },
  { id: 'zur', name: 'Zurich', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'mun', name: 'Munich', countryCode: 'DE', countryName: 'Germany' },
  { id: 'fra', name: 'Frankfurt', countryCode: 'DE', countryName: 'Germany' },
  { id: 'lis', name: 'Lisbon', countryCode: 'PT', countryName: 'Portugal' },
  { id: 'ath', name: 'Athens', countryCode: 'GR', countryName: 'Greece' },
  { id: 'ist', name: 'Istanbul', countryCode: 'TR', countryName: 'Turkey', popular: true },
  
  // Asian Cities
  { id: 'tok', name: 'Tokyo', countryCode: 'JP', countryName: 'Japan', popular: true },
  { id: 'seo', name: 'Seoul', countryCode: 'KR', countryName: 'South Korea', popular: true },
  { id: 'bkk', name: 'Bangkok', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { id: 'sin', name: 'Singapore', countryCode: 'SG', countryName: 'Singapore', popular: true },
  { id: 'hkg', name: 'Hong Kong', countryCode: 'HK', countryName: 'Hong Kong', popular: true },
  { id: 'dub', name: 'Dubai', countryCode: 'AE', countryName: 'United Arab Emirates', popular: true },
  { id: 'bej', name: 'Beijing', countryCode: 'CN', countryName: 'China' },
  { id: 'sha', name: 'Shanghai', countryCode: 'CN', countryName: 'China' },
  { id: 'kul', name: 'Kuala Lumpur', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'jkt', name: 'Jakarta', countryCode: 'ID', countryName: 'Indonesia' },
  { id: 'del', name: 'Delhi', countryCode: 'IN', countryName: 'India' },
  { id: 'mum', name: 'Mumbai', countryCode: 'IN', countryName: 'India' },
  { id: 'ban', name: 'Bangalore', countryCode: 'IN', countryName: 'India' },
  { id: 'che', name: 'Chennai', countryCode: 'IN', countryName: 'India' },
  { id: 'kol', name: 'Kolkata', countryCode: 'IN', countryName: 'India' },
  { id: 'hyd', name: 'Hyderabad', countryCode: 'IN', countryName: 'India' },
  { id: 'pun', name: 'Pune', countryCode: 'IN', countryName: 'India' },
  { id: 'man', name: 'Manila', countryCode: 'PH', countryName: 'Philippines' },
  { id: 'hcm', name: 'Ho Chi Minh City', countryCode: 'VN', countryName: 'Vietnam' },
  { id: 'han', name: 'Hanoi', countryCode: 'VN', countryName: 'Vietnam' },
  { id: 'phn', name: 'Phnom Penh', countryCode: 'KH', countryName: 'Cambodia' },
  { id: 'vte', name: 'Vientiane', countryCode: 'LA', countryName: 'Laos' },
  { id: 'rgn', name: 'Yangon', countryCode: 'MM', countryName: 'Myanmar' },
  { id: 'col', name: 'Colombo', countryCode: 'LK', countryName: 'Sri Lanka' },
  { id: 'kath', name: 'Kathmandu', countryCode: 'NP', countryName: 'Nepal' },
  { id: 'mal', name: 'Malé', countryCode: 'MV', countryName: 'Maldives' },
  { id: 'tai', name: 'Taipei', countryCode: 'TW', countryName: 'Taiwan' },
  { id: 'mac', name: 'Macau', countryCode: 'MO', countryName: 'Macau' },
  { id: 'ryd', name: 'Riyadh', countryCode: 'SA', countryName: 'Saudi Arabia' },
  { id: 'jed', name: 'Jeddah', countryCode: 'SA', countryName: 'Saudi Arabia' },
  { id: 'doh', name: 'Doha', countryCode: 'QA', countryName: 'Qatar' },
  { id: 'kuw', name: 'Kuwait City', countryCode: 'KW', countryName: 'Kuwait' },
  { id: 'man', name: 'Manama', countryCode: 'BH', countryName: 'Bahrain' },
  { id: 'mus', name: 'Muscat', countryCode: 'OM', countryName: 'Oman' },
  { id: 'amm', name: 'Amman', countryCode: 'JO', countryName: 'Jordan' },
  { id: 'bey', name: 'Beirut', countryCode: 'LB', countryName: 'Lebanon' },
  { id: 'tel', name: 'Tel Aviv', countryCode: 'IL', countryName: 'Israel' },
  { id: 'jer', name: 'Jerusalem', countryCode: 'IL', countryName: 'Israel' },
  
  // Popular Asian Destinations
  { id: 'kyo', name: 'Kyoto', countryCode: 'JP', countryName: 'Japan', popular: true },
  { id: 'osa', name: 'Osaka', countryCode: 'JP', countryName: 'Japan', popular: true },
  { id: 'yok', name: 'Yokohama', countryCode: 'JP', countryName: 'Japan' },
  { id: 'nag', name: 'Nagoya', countryCode: 'JP', countryName: 'Japan' },
  { id: 'sap', name: 'Sapporo', countryCode: 'JP', countryName: 'Japan' },
  { id: 'fuk', name: 'Fukuoka', countryCode: 'JP', countryName: 'Japan' },
  { id: 'bus', name: 'Busan', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'inc', name: 'Incheon', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'dae', name: 'Daegu', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'dae', name: 'Daejeon', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'gwa', name: 'Gwangju', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'uls', name: 'Ulsan', countryCode: 'KR', countryName: 'South Korea' },
  { id: 'gui', name: 'Guangzhou', countryCode: 'CN', countryName: 'China' },
  { id: 'shen', name: 'Shenzhen', countryCode: 'CN', countryName: 'China' },
  { id: 'chen', name: 'Chengdu', countryCode: 'CN', countryName: 'China' },
  { id: 'wuh', name: 'Wuhan', countryCode: 'CN', countryName: 'China' },
  { id: 'xian', name: 'Xi\'an', countryCode: 'CN', countryName: 'China' },
  { id: 'nan', name: 'Nanjing', countryCode: 'CN', countryName: 'China' },
  { id: 'tia', name: 'Tianjin', countryCode: 'CN', countryName: 'China' },
  { id: 'qin', name: 'Qingdao', countryCode: 'CN', countryName: 'China' },
  { id: 'dal', name: 'Dalian', countryCode: 'CN', countryName: 'China' },
  { id: 'ning', name: 'Ningbo', countryCode: 'CN', countryName: 'China' },
  { id: 'xiam', name: 'Xiamen', countryCode: 'CN', countryName: 'China' },
  { id: 'fuz', name: 'Fuzhou', countryCode: 'CN', countryName: 'China' },
  { id: 'hef', name: 'Hefei', countryCode: 'CN', countryName: 'China' },
  { id: 'kun', name: 'Kunming', countryCode: 'CN', countryName: 'China' },
  { id: 'chang', name: 'Changsha', countryCode: 'CN', countryName: 'China' },
  { id: 'zhe', name: 'Zhengzhou', countryCode: 'CN', countryName: 'China' },
  { id: 'jin', name: 'Jinan', countryCode: 'CN', countryName: 'China' },
  { id: 'tai', name: 'Taiyuan', countryCode: 'CN', countryName: 'China' },
  { id: 'shi', name: 'Shijiazhuang', countryCode: 'CN', countryName: 'China' },
  { id: 'har', name: 'Harbin', countryCode: 'CN', countryName: 'China' },
  { id: 'chang', name: 'Changchun', countryCode: 'CN', countryName: 'China' },
  { id: 'shen', name: 'Shenyang', countryCode: 'CN', countryName: 'China' },
  { id: 'hoh', name: 'Hohhot', countryCode: 'CN', countryName: 'China' },
  { id: 'yinch', name: 'Yinchuan', countryCode: 'CN', countryName: 'China' },
  { id: 'xini', name: 'Xining', countryCode: 'CN', countryName: 'China' },
  { id: 'lanz', name: 'Lanzhou', countryCode: 'CN', countryName: 'China' },
  { id: 'urum', name: 'Ürümqi', countryCode: 'CN', countryName: 'China' },
  { id: 'lhasa', name: 'Lhasa', countryCode: 'CN', countryName: 'China' },
  { id: 'chi', name: 'Chiang Mai', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { id: 'phu', name: 'Phuket', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { id: 'kra', name: 'Krabi', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { id: 'koh', name: 'Koh Samui', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { id: 'pai', name: 'Pai', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'sukh', name: 'Sukhothai', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'ayut', name: 'Ayutthaya', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'kan', name: 'Kanchanaburi', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'hua', name: 'Hua Hin', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'patt', name: 'Pattaya', countryCode: 'TH', countryName: 'Thailand' },
  { id: 'pen', name: 'Penang', countryCode: 'MY', countryName: 'Malaysia', popular: true },
  { id: 'lang', name: 'Langkawi', countryCode: 'MY', countryName: 'Malaysia', popular: true },
  { id: 'mal', name: 'Malacca', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'joh', name: 'Johor Bahru', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'kuch', name: 'Kuching', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'kota', name: 'Kota Kinabalu', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'ipoh', name: 'Ipoh', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'alor', name: 'Alor Setar', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'kang', name: 'Kangar', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'kuala', name: 'Kuala Terengganu', countryCode: 'MY', countryName: 'Malaysia' },
  { id: 'bali', name: 'Bali', countryCode: 'ID', countryName: 'Indonesia', popular: true },
  { id: 'ceb', name: 'Cebu', countryCode: 'PH', countryName: 'Philippines', popular: true },
  { id: 'da', name: 'Da Nang', countryCode: 'VN', countryName: 'Vietnam', popular: true },
  { id: 'nha', name: 'Nha Trang', countryCode: 'VN', countryName: 'Vietnam', popular: true },
  { id: 'sien', name: 'Siem Reap', countryCode: 'KH', countryName: 'Cambodia', popular: true },
  { id: 'luang', name: 'Luang Prabang', countryCode: 'LA', countryName: 'Laos', popular: true },
  { id: 'mand', name: 'Mandalay', countryCode: 'MM', countryName: 'Myanmar', popular: true },
  { id: 'kandy', name: 'Kandy', countryCode: 'LK', countryName: 'Sri Lanka', popular: true },
  { id: 'pok', name: 'Pokhara', countryCode: 'NP', countryName: 'Nepal', popular: true },
  { id: 'thim', name: 'Thimphu', countryCode: 'BT', countryName: 'Bhutan' },
  { id: 'male', name: 'Malé', countryCode: 'MV', countryName: 'Maldives', popular: true },
  { id: 'kaoh', name: 'Kaohsiung', countryCode: 'TW', countryName: 'Taiwan' },
  
  // Popular European Destinations
  { id: 'ibi', name: 'Ibiza', countryCode: 'ES', countryName: 'Spain', popular: true },
  { id: 'mal', name: 'Mallorca', countryCode: 'ES', countryName: 'Spain', popular: true },
  { id: 'sev', name: 'Seville', countryCode: 'ES', countryName: 'Spain', popular: true },
  { id: 'val', name: 'Valencia', countryCode: 'ES', countryName: 'Spain' },
  { id: 'bil', name: 'Bilbao', countryCode: 'ES', countryName: 'Spain' },
  { id: 'san', name: 'San Sebastian', countryCode: 'ES', countryName: 'Spain' },
  { id: 'cor', name: 'Córdoba', countryCode: 'ES', countryName: 'Spain' },
  { id: 'gra', name: 'Granada', countryCode: 'ES', countryName: 'Spain' },
  { id: 'tol', name: 'Toledo', countryCode: 'ES', countryName: 'Spain' },
  { id: 'sag', name: 'Sagrada Familia', countryCode: 'ES', countryName: 'Spain' },
  { id: 'flo', name: 'Florence', countryCode: 'IT', countryName: 'Italy', popular: true },
  { id: 'ven', name: 'Venice', countryCode: 'IT', countryName: 'Italy', popular: true },
  { id: 'nap', name: 'Naples', countryCode: 'IT', countryName: 'Italy' },
  { id: 'bol', name: 'Bologna', countryCode: 'IT', countryName: 'Italy' },
  { id: 'tur', name: 'Turin', countryCode: 'IT', countryName: 'Italy' },
  { id: 'gen', name: 'Genoa', countryCode: 'IT', countryName: 'Italy' },
  { id: 'pal', name: 'Palermo', countryCode: 'IT', countryName: 'Italy' },
  { id: 'cat', name: 'Catania', countryCode: 'IT', countryName: 'Italy' },
  { id: 'ver', name: 'Verona', countryCode: 'IT', countryName: 'Italy' },
  { id: 'pad', name: 'Padua', countryCode: 'IT', countryName: 'Italy' },
  { id: 'mar', name: 'Marseille', countryCode: 'FR', countryName: 'France', popular: true },
  { id: 'lyo', name: 'Lyon', countryCode: 'FR', countryName: 'France' },
  { id: 'tou', name: 'Toulouse', countryCode: 'FR', countryName: 'France' },
  { id: 'nic', name: 'Nice', countryCode: 'FR', countryName: 'France', popular: true },
  { id: 'str', name: 'Strasbourg', countryCode: 'FR', countryName: 'France' },
  { id: 'bor', name: 'Bordeaux', countryCode: 'FR', countryName: 'France' },
  { id: 'lil', name: 'Lille', countryCode: 'FR', countryName: 'France' },
  { id: 'ren', name: 'Rennes', countryCode: 'FR', countryName: 'France' },
  { id: 'mon', name: 'Montpellier', countryCode: 'FR', countryName: 'France' },
  { id: 'nanc', name: 'Nancy', countryCode: 'FR', countryName: 'France' },
  { id: 'ham', name: 'Hamburg', countryCode: 'DE', countryName: 'Germany' },
  { id: 'col', name: 'Cologne', countryCode: 'DE', countryName: 'Germany' },
  { id: 'stu', name: 'Stuttgart', countryCode: 'DE', countryName: 'Germany' },
  { id: 'dus', name: 'Düsseldorf', countryCode: 'DE', countryName: 'Germany' },
  { id: 'lei', name: 'Leipzig', countryCode: 'DE', countryName: 'Germany' },
  { id: 'dre', name: 'Dresden', countryCode: 'DE', countryName: 'Germany' },
  { id: 'han', name: 'Hannover', countryCode: 'DE', countryName: 'Germany' },
  { id: 'nur', name: 'Nuremberg', countryCode: 'DE', countryName: 'Germany' },
  { id: 'man', name: 'Manchester', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'bir', name: 'Birmingham', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'liv', name: 'Liverpool', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'lea', name: 'Leeds', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'she', name: 'Sheffield', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'bri', name: 'Bristol', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'edi', name: 'Edinburgh', countryCode: 'GB', countryName: 'United Kingdom', popular: true },
  { id: 'gla', name: 'Glasgow', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'bel', name: 'Belfast', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'car', name: 'Cardiff', countryCode: 'GB', countryName: 'United Kingdom' },
  { id: 'rot', name: 'Rotterdam', countryCode: 'NL', countryName: 'Netherlands' },
  { id: 'hag', name: 'The Hague', countryCode: 'NL', countryName: 'Netherlands' },
  { id: 'utr', name: 'Utrecht', countryCode: 'NL', countryName: 'Netherlands' },
  { id: 'eind', name: 'Eindhoven', countryCode: 'NL', countryName: 'Netherlands' },
  { id: 'til', name: 'Tilburg', countryCode: 'NL', countryName: 'Netherlands' },
  { id: 'gen', name: 'Geneva', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'bas', name: 'Basel', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'ber', name: 'Bern', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'luc', name: 'Lucerne', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'laus', name: 'Lausanne', countryCode: 'CH', countryName: 'Switzerland' },
  { id: 'sal', name: 'Salzburg', countryCode: 'AT', countryName: 'Austria', popular: true },
  { id: 'inz', name: 'Innsbruck', countryCode: 'AT', countryName: 'Austria' },
  { id: 'gra', name: 'Graz', countryCode: 'AT', countryName: 'Austria' },
  { id: 'lin', name: 'Linz', countryCode: 'AT', countryName: 'Austria' },
  { id: 'bru', name: 'Brussels', countryCode: 'BE', countryName: 'Belgium' },
  { id: 'ant', name: 'Antwerp', countryCode: 'BE', countryName: 'Belgium' },
  { id: 'ghe', name: 'Ghent', countryCode: 'BE', countryName: 'Belgium' },
  { id: 'cha', name: 'Charleroi', countryCode: 'BE', countryName: 'Belgium' },
  { id: 'por', name: 'Porto', countryCode: 'PT', countryName: 'Portugal' },
  { id: 'coi', name: 'Coimbra', countryCode: 'PT', countryName: 'Portugal' },
  { id: 'bra', name: 'Braga', countryCode: 'PT', countryName: 'Portugal' },
  { id: 'faro', name: 'Faro', countryCode: 'PT', countryName: 'Portugal' },
  { id: 'the', name: 'Thessaloniki', countryCode: 'GR', countryName: 'Greece' },
  { id: 'pat', name: 'Patras', countryCode: 'GR', countryName: 'Greece' },
  { id: 'her', name: 'Heraklion', countryCode: 'GR', countryName: 'Greece' },
  { id: 'lar', name: 'Larissa', countryCode: 'GR', countryName: 'Greece' },
  { id: 'vol', name: 'Volos', countryCode: 'GR', countryName: 'Greece' },
  { id: 'osl', name: 'Oslo', countryCode: 'NO', countryName: 'Norway' },
  { id: 'ber', name: 'Bergen', countryCode: 'NO', countryName: 'Norway' },
  { id: 'tro', name: 'Trondheim', countryCode: 'NO', countryName: 'Norway' },
  { id: 'sta', name: 'Stavanger', countryCode: 'NO', countryName: 'Norway' },
  { id: 'sto', name: 'Stockholm', countryCode: 'SE', countryName: 'Sweden' },
  { id: 'got', name: 'Gothenburg', countryCode: 'SE', countryName: 'Sweden' },
  { id: 'mal', name: 'Malmö', countryCode: 'SE', countryName: 'Sweden' },
  { id: 'upp', name: 'Uppsala', countryCode: 'SE', countryName: 'Sweden' },
  { id: 'cop', name: 'Copenhagen', countryCode: 'DK', countryName: 'Denmark' },
  { id: 'aar', name: 'Aarhus', countryCode: 'DK', countryName: 'Denmark' },
  { id: 'ode', name: 'Odense', countryCode: 'DK', countryName: 'Denmark' },
  { id: 'aal', name: 'Aalborg', countryCode: 'DK', countryName: 'Denmark' },
  { id: 'hel', name: 'Helsinki', countryCode: 'FI', countryName: 'Finland' },
  { id: 'tam', name: 'Tampere', countryCode: 'FI', countryName: 'Finland' },
  { id: 'tur', name: 'Turku', countryCode: 'FI', countryName: 'Finland' },
  { id: 'oul', name: 'Oulu', countryCode: 'FI', countryName: 'Finland' },
  { id: 'rey', name: 'Reykjavik', countryCode: 'IS', countryName: 'Iceland', popular: true },
  { id: 'kop', name: 'Kópavogur', countryCode: 'IS', countryName: 'Iceland' },
  { id: 'haf', name: 'Hafnarfjörður', countryCode: 'IS', countryName: 'Iceland' },
  { id: 'gar', name: 'Garðabær', countryCode: 'IS', countryName: 'Iceland' },
  { id: 'dub', name: 'Dublin', countryCode: 'IE', countryName: 'Ireland' },
  { id: 'cor', name: 'Cork', countryCode: 'IE', countryName: 'Ireland' },
  { id: 'gal', name: 'Galway', countryCode: 'IE', countryName: 'Ireland' },
  { id: 'lim', name: 'Limerick', countryCode: 'IE', countryName: 'Ireland' },
  { id: 'wro', name: 'Wrocław', countryCode: 'PL', countryName: 'Poland' },
  { id: 'kra', name: 'Kraków', countryCode: 'PL', countryName: 'Poland', popular: true },
  { id: 'gda', name: 'Gdańsk', countryCode: 'PL', countryName: 'Poland' },
  { id: 'poz', name: 'Poznań', countryCode: 'PL', countryName: 'Poland' },
  { id: 'lub', name: 'Lublin', countryCode: 'PL', countryName: 'Poland' },
  { id: 'zag', name: 'Zagreb', countryCode: 'HR', countryName: 'Croatia' },
  { id: 'spl', name: 'Split', countryCode: 'HR', countryName: 'Croatia', popular: true },
  { id: 'rij', name: 'Rijeka', countryCode: 'HR', countryName: 'Croatia' },
  { id: 'osij', name: 'Osijek', countryCode: 'HR', countryName: 'Croatia' },
  { id: 'bel', name: 'Belgrade', countryCode: 'RS', countryName: 'Serbia' },
  { id: 'nov', name: 'Novi Sad', countryCode: 'RS', countryName: 'Serbia' },
  { id: 'nis', name: 'Niš', countryCode: 'RS', countryName: 'Serbia' },
  { id: 'kra', name: 'Kragujevac', countryCode: 'RS', countryName: 'Serbia' },
  { id: 'sof', name: 'Sofia', countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'plo', name: 'Plovdiv', countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'var', name: 'Varna', countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'bur', name: 'Burgas', countryCode: 'BG', countryName: 'Bulgaria' },
  { id: 'buc', name: 'Bucharest', countryCode: 'RO', countryName: 'Romania' },
  { id: 'cla', name: 'Cluj-Napoca', countryCode: 'RO', countryName: 'Romania' },
  { id: 'tim', name: 'Timișoara', countryCode: 'RO', countryName: 'Romania' },
  { id: 'ias', name: 'Iași', countryCode: 'RO', countryName: 'Romania' },
  { id: 'bra', name: 'Bratislava', countryCode: 'SK', countryName: 'Slovakia' },
  { id: 'kos', name: 'Košice', countryCode: 'SK', countryName: 'Slovakia' },
  { id: 'pre', name: 'Prešov', countryCode: 'SK', countryName: 'Slovakia' },
  { id: 'nit', name: 'Nitra', countryCode: 'SK', countryName: 'Slovakia' },
  { id: 'lju', name: 'Ljubljana', countryCode: 'SI', countryName: 'Slovenia' },
  { id: 'mar', name: 'Maribor', countryCode: 'SI', countryName: 'Slovenia' },
  { id: 'cel', name: 'Celje', countryCode: 'SI', countryName: 'Slovenia' },
  { id: 'kra', name: 'Kranj', countryCode: 'SI', countryName: 'Slovenia' },
  { id: 'vil', name: 'Vilnius', countryCode: 'LT', countryName: 'Lithuania' },
  { id: 'kau', name: 'Kaunas', countryCode: 'LT', countryName: 'Lithuania' },
  { id: 'kla', name: 'Klaipėda', countryCode: 'LT', countryName: 'Lithuania' },
  { id: 'sia', name: 'Šiauliai', countryCode: 'LT', countryName: 'Lithuania' },
  { id: 'rig', name: 'Riga', countryCode: 'LV', countryName: 'Latvia' },
  { id: 'dau', name: 'Daugavpils', countryCode: 'LV', countryName: 'Latvia' },
  { id: 'lie', name: 'Liepāja', countryCode: 'LV', countryName: 'Latvia' },
  { id: 'jel', name: 'Jelgava', countryCode: 'LV', countryName: 'Latvia' },
  { id: 'tal', name: 'Tallinn', countryCode: 'EE', countryName: 'Estonia' },
  { id: 'tar', name: 'Tartu', countryCode: 'EE', countryName: 'Estonia' },
  { id: 'nar', name: 'Narva', countryCode: 'EE', countryName: 'Estonia' },
  { id: 'par', name: 'Pärnu', countryCode: 'EE', countryName: 'Estonia' },
  { id: 'mos', name: 'Moscow', countryCode: 'RU', countryName: 'Russia' },
  { id: 'sai', name: 'Saint Petersburg', countryCode: 'RU', countryName: 'Russia' },
  { id: 'nov', name: 'Novosibirsk', countryCode: 'RU', countryName: 'Russia' },
  { id: 'yek', name: 'Yekaterinburg', countryCode: 'RU', countryName: 'Russia' },
  { id: 'kie', name: 'Kyiv', countryCode: 'UA', countryName: 'Ukraine' },
  { id: 'kha', name: 'Kharkiv', countryCode: 'UA', countryName: 'Ukraine' },
  { id: 'od', name: 'Odesa', countryCode: 'UA', countryName: 'Ukraine' },
  { id: 'dn', name: 'Dnipro', countryCode: 'UA', countryName: 'Ukraine' },
  
  // Other Cities
  { id: 'tor', name: 'Toronto', countryCode: 'CA', countryName: 'Canada', popular: true },
  { id: 'van', name: 'Vancouver', countryCode: 'CA', countryName: 'Canada' },
  { id: 'mon', name: 'Montreal', countryCode: 'CA', countryName: 'Canada' },
  { id: 'cal', name: 'Calgary', countryCode: 'CA', countryName: 'Canada' },
  { id: 'ott', name: 'Ottawa', countryCode: 'CA', countryName: 'Canada' },
  { id: 'edm', name: 'Edmonton', countryCode: 'CA', countryName: 'Canada' },
  { id: 'win', name: 'Winnipeg', countryCode: 'CA', countryName: 'Canada' },
  { id: 'que', name: 'Quebec City', countryCode: 'CA', countryName: 'Canada' },
  { id: 'ham', name: 'Hamilton', countryCode: 'CA', countryName: 'Canada' },
  { id: 'kit', name: 'Kitchener', countryCode: 'CA', countryName: 'Canada' },
  { id: 'lon', name: 'London', countryCode: 'CA', countryName: 'Canada' },
  { id: 'vic', name: 'Victoria', countryCode: 'CA', countryName: 'Canada' },
  { id: 'hal', name: 'Halifax', countryCode: 'CA', countryName: 'Canada' },
  { id: 'syd', name: 'Sydney', countryCode: 'AU', countryName: 'Australia', popular: true },
  { id: 'mel', name: 'Melbourne', countryCode: 'AU', countryName: 'Australia' },
  { id: 'bri', name: 'Brisbane', countryCode: 'AU', countryName: 'Australia' },
  { id: 'per', name: 'Perth', countryCode: 'AU', countryName: 'Australia' },
  { id: 'ade', name: 'Adelaide', countryCode: 'AU', countryName: 'Australia' },
  { id: 'dar', name: 'Darwin', countryCode: 'AU', countryName: 'Australia' },
  { id: 'hob', name: 'Hobart', countryCode: 'AU', countryName: 'Australia' },
  { id: 'auc', name: 'Auckland', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'wel', name: 'Wellington', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'chr', name: 'Christchurch', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'ham', name: 'Hamilton', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'dun', name: 'Dunedin', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'pal', name: 'Palmerston North', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'nap', name: 'Napier', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'rot', name: 'Rotorua', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'taur', name: 'Tauranga', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'gis', name: 'Gisborne', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'nelson', name: 'Nelson', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'inver', name: 'Invercargill', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'new', name: 'New Plymouth', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'wha', name: 'Whangarei', countryCode: 'NZ', countryName: 'New Zealand' },
  { id: 'sao', name: 'São Paulo', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'rio', name: 'Rio de Janeiro', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'bsa', name: 'Brasília', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'sal', name: 'Salvador', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'for', name: 'Fortaleza', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'bel', name: 'Belo Horizonte', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'rec', name: 'Recife', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'por', name: 'Porto Alegre', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'cur', name: 'Curitiba', countryCode: 'BR', countryName: 'Brazil' },
  { id: 'bue', name: 'Buenos Aires', countryCode: 'AR', countryName: 'Argentina' },
  { id: 'cor', name: 'Córdoba', countryCode: 'AR', countryName: 'Argentina' },
  { id: 'ros', name: 'Rosario', countryCode: 'AR', countryName: 'Argentina' },
  { id: 'men', name: 'Mendoza', countryCode: 'AR', countryName: 'Argentina' },
  { id: 'lim', name: 'Lima', countryCode: 'PE', countryName: 'Peru' },
  { id: 'are', name: 'Arequipa', countryCode: 'PE', countryName: 'Peru' },
  { id: 'tru', name: 'Trujillo', countryCode: 'PE', countryName: 'Peru' },
  { id: 'cus', name: 'Cusco', countryCode: 'PE', countryName: 'Peru' },
  { id: 'bog', name: 'Bogotá', countryCode: 'CO', countryName: 'Colombia' },
  { id: 'med', name: 'Medellín', countryCode: 'CO', countryName: 'Colombia' },
  { id: 'cal', name: 'Cali', countryCode: 'CO', countryName: 'Colombia' },
  { id: 'bar', name: 'Barranquilla', countryCode: 'CO', countryName: 'Colombia' },
  { id: 'scl', name: 'Santiago', countryCode: 'CL', countryName: 'Chile' },
  { id: 'val', name: 'Valparaíso', countryCode: 'CL', countryName: 'Chile' },
  { id: 'con', name: 'Concepción', countryCode: 'CL', countryName: 'Chile' },
  { id: 'car', name: 'Caracas', countryCode: 'VE', countryName: 'Venezuela' },
  { id: 'mar', name: 'Maracaibo', countryCode: 'VE', countryName: 'Venezuela' },
  { id: 'val', name: 'Valencia', countryCode: 'VE', countryName: 'Venezuela' },
  { id: 'qui', name: 'Quito', countryCode: 'EC', countryName: 'Ecuador' },
  { id: 'guy', name: 'Guayaquil', countryCode: 'EC', countryName: 'Ecuador' },
  { id: 'lap', name: 'La Paz', countryCode: 'BO', countryName: 'Bolivia' },
  { id: 'suc', name: 'Sucre', countryCode: 'BO', countryName: 'Bolivia' },
  { id: 'santa', name: 'Santa Cruz', countryCode: 'BO', countryName: 'Bolivia' },
  { id: 'asu', name: 'Asunción', countryCode: 'PY', countryName: 'Paraguay' },
  { id: 'mon', name: 'Montevideo', countryCode: 'UY', countryName: 'Uruguay' },
  { id: 'geo', name: 'Georgetown', countryCode: 'GY', countryName: 'Guyana' },
  { id: 'par', name: 'Paramaribo', countryCode: 'SR', countryName: 'Suriname' },
  { id: 'cay', name: 'Cayenne', countryCode: 'GF', countryName: 'French Guiana' },
  { id: 'jhb', name: 'Johannesburg', countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'cpt', name: 'Cape Town', countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'dur', name: 'Durban', countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'pre', name: 'Pretoria', countryCode: 'ZA', countryName: 'South Africa' },
  { id: 'cai', name: 'Cairo', countryCode: 'EG', countryName: 'Egypt' },
  { id: 'ale', name: 'Alexandria', countryCode: 'EG', countryName: 'Egypt' },
  { id: 'giz', name: 'Giza', countryCode: 'EG', countryName: 'Egypt' },
  { id: 'cas', name: 'Casablanca', countryCode: 'MA', countryName: 'Morocco' },
  { id: 'rab', name: 'Rabat', countryCode: 'MA', countryName: 'Morocco' },
  { id: 'fes', name: 'Fez', countryCode: 'MA', countryName: 'Morocco' },
  { id: 'mar', name: 'Marrakech', countryCode: 'MA', countryName: 'Morocco' },
  { id: 'nai', name: 'Nairobi', countryCode: 'KE', countryName: 'Kenya' },
  { id: 'mom', name: 'Mombasa', countryCode: 'KE', countryName: 'Kenya' },
  { id: 'dar', name: 'Dar es Salaam', countryCode: 'TZ', countryName: 'Tanzania' },
  { id: 'dod', name: 'Dodoma', countryCode: 'TZ', countryName: 'Tanzania' },
  { id: 'zanz', name: 'Zanzibar', countryCode: 'TZ', countryName: 'Tanzania' },
  { id: 'lag', name: 'Lagos', countryCode: 'NG', countryName: 'Nigeria' },
  { id: 'abu', name: 'Abuja', countryCode: 'NG', countryName: 'Nigeria' },
  { id: 'kan', name: 'Kano', countryCode: 'NG', countryName: 'Nigeria' },
  { id: 'acc', name: 'Accra', countryCode: 'GH', countryName: 'Ghana' },
  { id: 'kum', name: 'Kumasi', countryCode: 'GH', countryName: 'Ghana' },
  { id: 'add', name: 'Addis Ababa', countryCode: 'ET', countryName: 'Ethiopia' },
  { id: 'dir', name: 'Dire Dawa', countryCode: 'ET', countryName: 'Ethiopia' },
  { id: 'kam', name: 'Kampala', countryCode: 'UG', countryName: 'Uganda' },
  { id: 'kig', name: 'Kigali', countryCode: 'RW', countryName: 'Rwanda' },
  { id: 'gab', name: 'Gaborone', countryCode: 'BW', countryName: 'Botswana' },
  { id: 'win', name: 'Windhoek', countryCode: 'NA', countryName: 'Namibia' },
  { id: 'lus', name: 'Lusaka', countryCode: 'ZM', countryName: 'Zambia' },
  { id: 'har', name: 'Harare', countryCode: 'ZW', countryName: 'Zimbabwe' },
  { id: 'bul', name: 'Bulawayo', countryCode: 'ZW', countryName: 'Zimbabwe' },
  { id: 'lil', name: 'Lilongwe', countryCode: 'MW', countryName: 'Malawi' },
  { id: 'bla', name: 'Blantyre', countryCode: 'MW', countryName: 'Malawi' },
  { id: 'map', name: 'Maputo', countryCode: 'MZ', countryName: 'Mozambique' },
  { id: 'beir', name: 'Beira', countryCode: 'MZ', countryName: 'Mozambique' },
  { id: 'ant', name: 'Antananarivo', countryCode: 'MG', countryName: 'Madagascar' },
  { id: 'tam', name: 'Tamatave', countryCode: 'MG', countryName: 'Madagascar' },
  { id: 'port', name: 'Port Louis', countryCode: 'MU', countryName: 'Mauritius' },
  { id: 'vic', name: 'Victoria', countryCode: 'SC', countryName: 'Seychelles' },
  { id: 'sai', name: 'Saint-Denis', countryCode: 'RE', countryName: 'Réunion' },
  { id: 'tun', name: 'Tunis', countryCode: 'TN', countryName: 'Tunisia' },
  { id: 'sfa', name: 'Sfax', countryCode: 'TN', countryName: 'Tunisia' },
  { id: 'alg', name: 'Algiers', countryCode: 'DZ', countryName: 'Algeria' },
  { id: 'ora', name: 'Oran', countryCode: 'DZ', countryName: 'Algeria' },
  { id: 'trip', name: 'Tripoli', countryCode: 'LY', countryName: 'Libya' },
  { id: 'ben', name: 'Benghazi', countryCode: 'LY', countryName: 'Libya' },
  { id: 'kha', name: 'Khartoum', countryCode: 'SD', countryName: 'Sudan' },
  { id: 'por', name: 'Port Sudan', countryCode: 'SD', countryName: 'Sudan' },
  { id: 'jub', name: 'Juba', countryCode: 'SS', countryName: 'South Sudan' },
  { id: 'asm', name: 'Asmara', countryCode: 'ER', countryName: 'Eritrea' },
  { id: 'dji', name: 'Djibouti', countryCode: 'DJ', countryName: 'Djibouti' },
  { id: 'mog', name: 'Mogadishu', countryCode: 'SO', countryName: 'Somalia' },
  { id: 'dak', name: 'Dakar', countryCode: 'SN', countryName: 'Senegal' },
  { id: 'thi', name: 'Thiès', countryCode: 'SN', countryName: 'Senegal' },
  { id: 'bam', name: 'Bamako', countryCode: 'ML', countryName: 'Mali' },
  { id: 'timb', name: 'Timbuktu', countryCode: 'ML', countryName: 'Mali' },
  { id: 'oua', name: 'Ouagadougou', countryCode: 'BF', countryName: 'Burkina Faso' },
  { id: 'bob', name: 'Bobo-Dioulasso', countryCode: 'BF', countryName: 'Burkina Faso' },
  { id: 'nia', name: 'Niamey', countryCode: 'NE', countryName: 'Niger' },
  { id: 'zind', name: 'Zinder', countryCode: 'NE', countryName: 'Niger' },
  { id: 'njam', name: 'N\'Djamena', countryCode: 'TD', countryName: 'Chad' },
  { id: 'moun', name: 'Moundou', countryCode: 'TD', countryName: 'Chad' },
  { id: 'yao', name: 'Yaoundé', countryCode: 'CM', countryName: 'Cameroon' },
  { id: 'dou', name: 'Douala', countryCode: 'CM', countryName: 'Cameroon' },
  { id: 'ban', name: 'Bangui', countryCode: 'CF', countryName: 'Central African Republic' },
  { id: 'kin', name: 'Kinshasa', countryCode: 'CD', countryName: 'Democratic Republic of the Congo' },
  { id: 'lub', name: 'Lubumbashi', countryCode: 'CD', countryName: 'Democratic Republic of the Congo' },
  { id: 'braz', name: 'Brazzaville', countryCode: 'CG', countryName: 'Republic of the Congo' },
  { id: 'poin', name: 'Pointe-Noire', countryCode: 'CG', countryName: 'Republic of the Congo' },
  { id: 'lib', name: 'Libreville', countryCode: 'GA', countryName: 'Gabon' },
  { id: 'port', name: 'Port-Gentil', countryCode: 'GA', countryName: 'Gabon' },
  { id: 'mal', name: 'Malabo', countryCode: 'GQ', countryName: 'Equatorial Guinea' },
  { id: 'bat', name: 'Bata', countryCode: 'GQ', countryName: 'Equatorial Guinea' },
  { id: 'sao', name: 'São Tomé', countryCode: 'ST', countryName: 'São Tomé and Príncipe' },
  { id: 'lua', name: 'Luanda', countryCode: 'AO', countryName: 'Angola' },
  { id: 'hub', name: 'Huambo', countryCode: 'AO', countryName: 'Angola' },
  { id: 'pra', name: 'Praia', countryCode: 'CV', countryName: 'Cape Verde' },
  { id: 'min', name: 'Mindelo', countryCode: 'CV', countryName: 'Cape Verde' },
  { id: 'bis', name: 'Bissau', countryCode: 'GW', countryName: 'Guinea-Bissau' },
  { id: 'con', name: 'Conakry', countryCode: 'GN', countryName: 'Guinea' },
  { id: 'fre', name: 'Freetown', countryCode: 'SL', countryName: 'Sierra Leone' },
  { id: 'bo', name: 'Bo', countryCode: 'SL', countryName: 'Sierra Leone' },
  { id: 'mon', name: 'Monrovia', countryCode: 'LR', countryName: 'Liberia' },
  { id: 'gbar', name: 'Gbarnga', countryCode: 'LR', countryName: 'Liberia' },
  { id: 'yam', name: 'Yamoussoukro', countryCode: 'CI', countryName: 'Ivory Coast' },
  { id: 'abid', name: 'Abidjan', countryCode: 'CI', countryName: 'Ivory Coast' },
  { id: 'banj', name: 'Banjul', countryCode: 'GM', countryName: 'Gambia' },
  { id: 'ser', name: 'Serekunda', countryCode: 'GM', countryName: 'Gambia' },
  { id: 'gite', name: 'Gitega', countryCode: 'BI', countryName: 'Burundi' },
  { id: 'buj', name: 'Bujumbura', countryCode: 'BI', countryName: 'Burundi' },
  { id: 'mor', name: 'Moroni', countryCode: 'KM', countryName: 'Comoros' },
  { id: 'mam', name: 'Mamoudzou', countryCode: 'YT', countryName: 'Mayotte' },
];

export const AIRPORTS: Airport[] = [
  // US Airports
  { iata: 'JFK', icao: 'KJFK', name: 'John F. Kennedy International Airport', cityId: 'nyc', cityName: 'New York', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'LGA', icao: 'KLGA', name: 'LaGuardia Airport', cityId: 'nyc', cityName: 'New York', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'EWR', icao: 'KEWR', name: 'Newark Liberty International Airport', cityId: 'nyc', cityName: 'New York', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'LAX', icao: 'KLAX', name: 'Los Angeles International Airport', cityId: 'lax', cityName: 'Los Angeles', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'ORD', icao: 'KORD', name: 'O\'Hare International Airport', cityId: 'chi', cityName: 'Chicago', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'MDW', icao: 'KMDW', name: 'Midway International Airport', cityId: 'chi', cityName: 'Chicago', countryCode: 'US', countryName: 'United States' },
  { iata: 'MIA', icao: 'KMIA', name: 'Miami International Airport', cityId: 'mia', cityName: 'Miami', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'SFO', icao: 'KSFO', name: 'San Francisco International Airport', cityId: 'sfo', cityName: 'San Francisco', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'SEA', icao: 'KSEA', name: 'Seattle-Tacoma International Airport', cityId: 'sea', cityName: 'Seattle', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'BOS', icao: 'KBOS', name: 'Logan International Airport', cityId: 'bos', cityName: 'Boston', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'ATL', icao: 'KATL', name: 'Hartsfield-Jackson Atlanta International Airport', cityId: 'atl', cityName: 'Atlanta', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'DFW', icao: 'KDFW', name: 'Dallas/Fort Worth International Airport', cityId: 'dfw', cityName: 'Dallas', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'DEN', icao: 'KDEN', name: 'Denver International Airport', cityId: 'den', cityName: 'Denver', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'LAS', icao: 'KLAS', name: 'Harry Reid International Airport', cityId: 'las', cityName: 'Las Vegas', countryCode: 'US', countryName: 'United States', popular: true },
  { iata: 'PHX', icao: 'KPHX', name: 'Phoenix Sky Harbor International Airport', cityId: 'phx', cityName: 'Phoenix', countryCode: 'US', countryName: 'United States' },
  { iata: 'IAD', icao: 'KIAD', name: 'Washington Dulles International Airport', cityId: 'dc', cityName: 'Washington DC', countryCode: 'US', countryName: 'United States' },
  { iata: 'DCA', icao: 'KDCA', name: 'Ronald Reagan Washington National Airport', cityId: 'dc', cityName: 'Washington DC', countryCode: 'US', countryName: 'United States' },
  { iata: 'MCO', icao: 'KMCO', name: 'Orlando International Airport', cityId: 'orl', cityName: 'Orlando', countryCode: 'US', countryName: 'United States' },
  
  // European Airports
  { iata: 'LHR', icao: 'EGLL', name: 'Heathrow Airport', cityId: 'lon', cityName: 'London', countryCode: 'GB', countryName: 'United Kingdom', popular: true },
  { iata: 'LGW', icao: 'EGKK', name: 'Gatwick Airport', cityId: 'lon', cityName: 'London', countryCode: 'GB', countryName: 'United Kingdom' },
  { iata: 'STN', icao: 'EGSS', name: 'Stansted Airport', cityId: 'lon', cityName: 'London', countryCode: 'GB', countryName: 'United Kingdom' },
  { iata: 'CDG', icao: 'LFPG', name: 'Charles de Gaulle Airport', cityId: 'par', cityName: 'Paris', countryCode: 'FR', countryName: 'France', popular: true },
  { iata: 'ORY', icao: 'LFPO', name: 'Orly Airport', cityId: 'par', cityName: 'Paris', countryCode: 'FR', countryName: 'France' },
  { iata: 'FCO', icao: 'LIRF', name: 'Leonardo da Vinci International Airport', cityId: 'rom', cityName: 'Rome', countryCode: 'IT', countryName: 'Italy', popular: true },
  { iata: 'BCN', icao: 'LEBL', name: 'Barcelona-El Prat Airport', cityId: 'bcn', cityName: 'Barcelona', countryCode: 'ES', countryName: 'Spain', popular: true },
  { iata: 'AMS', icao: 'EHAM', name: 'Amsterdam Airport Schiphol', cityId: 'ams', cityName: 'Amsterdam', countryCode: 'NL', countryName: 'Netherlands', popular: true },
  { iata: 'FRA', icao: 'EDDF', name: 'Frankfurt Airport', cityId: 'fra', cityName: 'Frankfurt', countryCode: 'DE', countryName: 'Germany', popular: true },
  { iata: 'MUC', icao: 'EDDM', name: 'Munich Airport', cityId: 'mun', cityName: 'Munich', countryCode: 'DE', countryName: 'Germany' },
  { iata: 'VIE', icao: 'LOWW', name: 'Vienna International Airport', cityId: 'vie', cityName: 'Vienna', countryCode: 'AT', countryName: 'Austria', popular: true },
  { iata: 'ZUR', icao: 'LSZH', name: 'Zurich Airport', cityId: 'zur', cityName: 'Zurich', countryCode: 'CH', countryName: 'Switzerland' },
  
  // Asian Airports
  { iata: 'NRT', icao: 'RJAA', name: 'Narita International Airport', cityId: 'tok', cityName: 'Tokyo', countryCode: 'JP', countryName: 'Japan', popular: true },
  { iata: 'HND', icao: 'RJTT', name: 'Haneda Airport', cityId: 'tok', cityName: 'Tokyo', countryCode: 'JP', countryName: 'Japan' },
  { iata: 'ICN', icao: 'RKSI', name: 'Incheon International Airport', cityId: 'seo', cityName: 'Seoul', countryCode: 'KR', countryName: 'South Korea', popular: true },
  { iata: 'BKK', icao: 'VTBS', name: 'Suvarnabhumi Airport', cityId: 'bkk', cityName: 'Bangkok', countryCode: 'TH', countryName: 'Thailand', popular: true },
  { iata: 'SIN', icao: 'WSSS', name: 'Singapore Changi Airport', cityId: 'sin', cityName: 'Singapore', countryCode: 'SG', countryName: 'Singapore', popular: true },
  { iata: 'HKG', icao: 'VHHH', name: 'Hong Kong International Airport', cityId: 'hkg', cityName: 'Hong Kong', countryCode: 'HK', countryName: 'Hong Kong', popular: true },
  { iata: 'DXB', icao: 'OMDB', name: 'Dubai International Airport', cityId: 'dub', cityName: 'Dubai', countryCode: 'AE', countryName: 'United Arab Emirates', popular: true },
  { iata: 'PEK', icao: 'ZBAA', name: 'Beijing Capital International Airport', cityId: 'bej', cityName: 'Beijing', countryCode: 'CN', countryName: 'China' },
  { iata: 'PVG', icao: 'ZSPD', name: 'Shanghai Pudong International Airport', cityId: 'sha', cityName: 'Shanghai', countryCode: 'CN', countryName: 'China' },
  
  // Other Airports
  { iata: 'YYZ', icao: 'CYYZ', name: 'Toronto Pearson International Airport', cityId: 'tor', cityName: 'Toronto', countryCode: 'CA', countryName: 'Canada', popular: true },
  { iata: 'YVR', icao: 'CYVR', name: 'Vancouver International Airport', cityId: 'van', cityName: 'Vancouver', countryCode: 'CA', countryName: 'Canada' },
  { iata: 'SYD', icao: 'YSSY', name: 'Sydney Kingsford Smith Airport', cityId: 'syd', cityName: 'Sydney', countryCode: 'AU', countryName: 'Australia', popular: true },
  { iata: 'MEL', icao: 'YMML', name: 'Melbourne Airport', cityId: 'mel', cityName: 'Melbourne', countryCode: 'AU', countryName: 'Australia' },
];

// Search functions
export function searchAirports(query: string): Airport[] {
  if (!query || query.length < 2) {
    return AIRPORTS.filter(a => a.popular).slice(0, 12);
  }
  
  const lowerQuery = query.toLowerCase();
  return AIRPORTS.filter(airport => 
    airport.iata.toLowerCase().includes(lowerQuery) ||
    airport.name.toLowerCase().includes(lowerQuery) ||
    airport.cityName.toLowerCase().includes(lowerQuery) ||
    airport.countryName.toLowerCase().includes(lowerQuery)
  ).slice(0, 20);
}

export function searchCities(query: string): City[] {
  if (!query || query.length < 2) {
    return CITIES.filter(c => c.popular).slice(0, 12);
  }
  
  const lowerQuery = query.toLowerCase();
  return CITIES.filter(city => 
    city.name.toLowerCase().includes(lowerQuery) ||
    city.countryName.toLowerCase().includes(lowerQuery)
  ).slice(0, 20);
}

export function searchCountries(query: string): Country[] {
  if (!query || query.length < 2) {
    return COUNTRIES.slice(0, 12);
  }
  
  const lowerQuery = query.toLowerCase();
  return COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  ).slice(0, 20);
}

export function searchDestinations(query: string): (City | Country)[] {
  const cities = searchCities(query);
  const countries = searchCountries(query);
  
  // Combine and sort by relevance (popular items first)
  const combined = [...cities, ...countries];
  return combined.slice(0, 20);
}
